# "Symmetrizing" a matrix

This notebook walks you through how to implement simple functions that make a square matrix symmetric by copying the lower triangular part in its upper triangular part (after transposing).

## Getting started

We will use some functions that are part of our laff library (of which this function will become a part) as well as some routines from the FLAME API (Application Programming Interface) that allows us to write code that closely resembles how we typeset algorithms using the FLAME notation.  These functions are imported with the "import laff as laff" and "import flame" statements.

## Algorithm

<image src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/326SymmetrizeAlgorithm.png" alt="Make matrix into a triangular matrix" width="75%">

## The routine

Write your <br>
<code> Symmetrize_from_lower_triangle_unb_var1( A ) </code> <br>
routine, using the <a href="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/index.html"> Spark webpage </a>.

In [1]:
import flame
import laff as laff

def Symmetrize_from_lower_triangle_unb_var1(A):

    ATL, ATR, \
    ABL, ABR  = flame.part_2x2(A, \
                               0, 0, 'TL')

    while ATL.shape[0] < A.shape[0]:

        A00,  a01,     A02,  \
        a10t, alpha11, a12t, \
        A20,  a21,     A22   = flame.repart_2x2_to_3x3(ATL, ATR, \
                                                       ABL, ABR, \
                                                       1, 1, 'BR')

        #------------------------------------------------------------#

        laff.copy( a10t, a01 )

        #------------------------------------------------------------#

        ATL, ATR, \
        ABL, ABR  = flame.cont_with_3x3_to_2x2(A00,  a01,     A02,  \
                                               a10t, alpha11, a12t, \
                                               A20,  a21,     A22,  \
                                               'TL')

    flame.merge_2x2(ATL, ATR, \
                    ABL, ABR, A)





## Testing

Let's quickly test the routine by creating a 5 x 5 matrix and then executing the routine.

In [2]:
from numpy import random
from numpy import matrix

A = matrix( random.rand( 5,5 ) )

print( 'A before =' )
print( A )

A before =
[[0.38540878 0.47719194 0.11854039 0.519877   0.80586187]
 [0.61174567 0.59594884 0.27512261 0.91223396 0.83569662]
 [0.27934249 0.25818114 0.27248947 0.34409559 0.53809361]
 [0.36170055 0.47070328 0.54390411 0.60271339 0.2620656 ]
 [0.38593037 0.97678706 0.03148608 0.48344497 0.33911721]]


In [3]:
Symmetrize_from_lower_triangle_unb_var1( A )

print( 'A after =' )
print( A )

A after =
[[0.38540878 0.61174567 0.27934249 0.36170055 0.38593037]
 [0.61174567 0.59594884 0.25818114 0.47070328 0.97678706]
 [0.27934249 0.25818114 0.27248947 0.54390411 0.03148608]
 [0.36170055 0.47070328 0.54390411 0.60271339 0.48344497]
 [0.38593037 0.97678706 0.03148608 0.48344497 0.33911721]]


Bingo, it seems to work!

## Try it yourself (Homework 3.2.6.5)

Now, an alternative routine that sets the upper triangular part by rows.

Use the <a href="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/index.html"> Spark webpage </a> to generate the routine <br>
<code> Symmetrize_from_lower_triangle_unb_var2( A )</code>.<br>

In [4]:
import flame
import laff as laff

def Symmetrize_from_lower_triangle_unb_var2(A):

    ATL, ATR, \
    ABL, ABR  = flame.part_2x2(A, \
                               0, 0, 'TL')

    while ATL.shape[0] < A.shape[0]:

        A00,  a01,     A02,  \
        a10t, alpha11, a12t, \
        A20,  a21,     A22   = flame.repart_2x2_to_3x3(ATL, ATR, \
                                                       ABL, ABR, \
                                                       1, 1, 'BR')

        #------------------------------------------------------------#

        laff.copy( a21, a12t )

        #------------------------------------------------------------#

        ATL, ATR, \
        ABL, ABR  = flame.cont_with_3x3_to_2x2(A00,  a01,     A02,  \
                                               a10t, alpha11, a12t, \
                                               A20,  a21,     A22,  \
                                               'TL')

    flame.merge_2x2(ATL, ATR, \
                    ABL, ABR, A)






Test your routine with the following

In [5]:
from numpy import random
from numpy import matrix

A = matrix( random.rand( 5,5 ) )

print( 'A before =' )
print( A )

Symmetrize_from_lower_triangle_unb_var2( A )
print( 'A after =' )
print( A )

A before =
[[0.47834562 0.39737475 0.62796274 0.58049916 0.63401502]
 [0.68276646 0.00218469 0.61526664 0.79364245 0.77199596]
 [0.56797996 0.20836319 0.75004778 0.22409205 0.35141436]
 [0.62631338 0.64678803 0.47296022 0.50962458 0.52472075]
 [0.2227103  0.19431942 0.07999915 0.72925182 0.57986032]]
A after =
[[0.47834562 0.68276646 0.56797996 0.62631338 0.2227103 ]
 [0.68276646 0.00218469 0.20836319 0.64678803 0.19431942]
 [0.56797996 0.20836319 0.75004778 0.47296022 0.07999915]
 [0.62631338 0.64678803 0.47296022 0.50962458 0.72925182]
 [0.2227103  0.19431942 0.07999915 0.72925182 0.57986032]]


## Watch your code in action!

Copy and paste the code into <a href="http://edx-org-utaustinx.s3.amazonaws.com/UT501x/PictureFlame/PictureFLAME.html"> PictureFLAME </a>, a webpage where you can watch your routine in action.  Just cut and paste into the box.  

Disclaimer: we implemented a VERY simple interpreter.  If you do something wrong, we cannot guarantee the results.  But if you do it right, you are in for a treat.

If you want to reset the problem, just click in the box into which you pasted the code and hit "next" again.