# "Triangularizing" a matrix

This notebook walks you through how to implement simple functions that make a square matrix into a triangular matrix by setting the appropriate entries in the matrix to zero or one.

## Getting started

We will use some functions that are part of our laff library (of which this function will become a part) as well as some routines from the FLAME API (Application Programming Interface) that allows us to write code that closely resembles how we typeset algorithms using the FLAME notation.  These functions are imported with the "import laff as laff" and "import flame" statements.

## Algorithm

<image src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/324TriangularizeAlgorithm.png" alt="Make matrix into a triangular matrix" width="75%">

## The routine

Write your <br>
<code> Set_to_lower_triangular_matrix_unb_var1( A ) </code> <br>
routine, using the <a href="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/index.html"> Spark webpage </a>.

In [1]:
import flame
import laff as laff

def Set_to_lower_triangular_matrix_unb_var1(A):

    ATL, ATR, \
    ABL, ABR  = flame.part_2x2(A, \
                               0, 0, 'TL')

    while ATL.shape[0] < A.shape[0]:

        A00,  a01,     A02,  \
        a10t, alpha11, a12t, \
        A20,  a21,     A22   = flame.repart_2x2_to_3x3(ATL, ATR, \
                                                       ABL, ABR, \
                                                       1, 1, 'BR')

        #------------------------------------------------------------#

        laff.zerov( a01 )

        #------------------------------------------------------------#

        ATL, ATR, \
        ABL, ABR  = flame.cont_with_3x3_to_2x2(A00,  a01,     A02,  \
                                               a10t, alpha11, a12t, \
                                               A20,  a21,     A22,  \
                                               'TL')

    flame.merge_2x2(ATL, ATR, \
                    ABL, ABR, A)





## Testing

Let's quickly test the routine by creating a 5 x 5 matrix and then setting its strictly upper triangular part to zero, thus making it lower triangular.


In [2]:
from numpy import random
from numpy import matrix

A = matrix( random.rand( 5,5 ) )

print( 'A before =' )
print( A )

A before =
[[0.24924038 0.2237304  0.26530343 0.61866106 0.43690454]
 [0.881325   0.36343151 0.31767748 0.16750862 0.83309808]
 [0.24493654 0.80049347 0.00596198 0.95426211 0.59654186]
 [0.85788771 0.5610191  0.66082284 0.31586554 0.21329445]
 [0.48988289 0.44240261 0.01803631 0.71368463 0.86269925]]


In [3]:
Set_to_lower_triangular_matrix_unb_var1( A )

print( 'A after =' )
print( A )

A after =
[[0.24924038 0.         0.         0.         0.        ]
 [0.881325   0.36343151 0.         0.         0.        ]
 [0.24493654 0.80049347 0.00596198 0.         0.        ]
 [0.85788771 0.5610191  0.66082284 0.31586554 0.        ]
 [0.48988289 0.44240261 0.01803631 0.71368463 0.86269925]]


Bingo, it seems to work!

## Try it yourself (Homework 3.2.4.6)

Now, an alternative routine that accesses the matrix by rows.

Use the <a href="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/index.html"> Spark webpage </a> to generate the routine <br>
<code> Set_to_lower_triangular_matrix_unb_var2( A )</code>.<br>

In [4]:
import flame
import laff as laff

def Set_to_lower_triangular_matrix_unb_var2(A):

    ATL, ATR, \
    ABL, ABR  = flame.part_2x2(A, \
                               0, 0, 'TL')

    while ATL.shape[0] < A.shape[0]:

        A00,  a01,     A02,  \
        a10t, alpha11, a12t, \
        A20,  a21,     A22   = flame.repart_2x2_to_3x3(ATL, ATR, \
                                                       ABL, ABR, \
                                                       1, 1, 'BR')

        #------------------------------------------------------------#

        laff.zerov( a12t )

        #------------------------------------------------------------#

        ATL, ATR, \
        ABL, ABR  = flame.cont_with_3x3_to_2x2(A00,  a01,     A02,  \
                                               a10t, alpha11, a12t, \
                                               A20,  a21,     A22,  \
                                               'TL')

    flame.merge_2x2(ATL, ATR, \
                    ABL, ABR, A)






Test your routine with the following

In [5]:
from numpy import random
from numpy import matrix

A = matrix( random.rand( 5,5 ) )

print( 'A before =' )
print( A )

Set_to_lower_triangular_matrix_unb_var2( A )
print( 'A after =' )
print( A )

A before =
[[0.83911879 0.0413937  0.00570589 0.96588914 0.78123569]
 [0.12975093 0.62476353 0.5567724  0.51881308 0.85500886]
 [0.00321041 0.45185128 0.62583265 0.43993842 0.9224459 ]
 [0.32681499 0.42709059 0.40983251 0.24592335 0.00277185]
 [0.70902931 0.70061587 0.76985332 0.90508768 0.75375992]]
A after =
[[0.83911879 0.         0.         0.         0.        ]
 [0.12975093 0.62476353 0.         0.         0.        ]
 [0.00321041 0.45185128 0.62583265 0.         0.        ]
 [0.32681499 0.42709059 0.40983251 0.24592335 0.        ]
 [0.70902931 0.70061587 0.76985332 0.90508768 0.75375992]]


## Watch your code in action!

Copy and paste the code into <a href="http://edx-org-utaustinx.s3.amazonaws.com/UT501x/PictureFlame/PictureFLAME.html"> PictureFLAME </a>, a webpage where you can watch your routine in action.  Just cut and paste into the box.  

Disclaimer: we implemented a VERY simple interpreter.  If you do something wrong, we cannot guarantee the results.  But if you do it right, you are in for a treat.

If you want to reset the problem, just click in the box into which you pasted the code and hit "next" again.