# The Scale_a_matrix routine

This notebook walks you through how to implement a simple function that scales a matrix $ A $ by a scalar $ \beta $, overwriting $ A $.

## Getting started

We will use some functions that are part of our laff library (of which this function will become a part) as well as some routines from the FLAME API (Application Programming Interface) that allows us to write code that closely resembles how we typeset algorithms using the FLAME notation.  These functions are imported with the "import laff as laff" and "import flame" statements.

## Algorithm

<image src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/331ScaleMatrix.png" alt="Set matrix to zero algorithm" width="85%">

## The routine

The specific laff function we will use is laff.scal which, when given a row or column vector (stored as a 1 x n or n x 1 matrix) and a scalar scales that vector.  

Code the routine with the <a href="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/index.html"> Spark webpage </a>.

In [1]:
import flame
import laff as laff

def Scale_a_matrix_unb_var1(beta, A):

    AL, AR = flame.part_1x2(A, \
                            0, 'LEFT')

    while AL.shape[1] < A.shape[1]:

        A0, a1, A2 = flame.repart_1x2_to_1x3(AL, AR, \
                                             1, 'RIGHT')

        #------------------------------------------------------------#

        laff.scal( beta, a1 )

        #------------------------------------------------------------#

        AL, AR = flame.cont_with_1x3_to_1x2(A0, a1, A2, \
                                            'LEFT')

    flame.merge_1x2(AL, AR, A)





## Testing

Let's quickly test the routine by creating a 5 x 4 matrix and then scaling by a scalar.

In [2]:
from numpy import random
from numpy import matrix

beta = matrix( '2.' )
A = matrix( random.rand( 5,4 ) )

print( 'beta = ' )
print( beta )

print( 'A before =' )
print( A )

beta = 
[[2.]]
A before =
[[0.54132349 0.49850549 0.09899091 0.23352636]
 [0.60353164 0.17630215 0.1473723  0.75177106]
 [0.51139344 0.91632286 0.64401747 0.35842984]
 [0.16485562 0.42753971 0.95173093 0.50041139]
 [0.32452641 0.84402383 0.71321724 0.61024824]]


In [3]:
Scale_a_matrix_unb_var1( beta, A )

print( 'A after =' )
print( A )

A after =
[[1.08264697 0.99701098 0.19798182 0.46705273]
 [1.20706329 0.3526043  0.2947446  1.50354211]
 [1.02278688 1.83264571 1.28803493 0.71685969]
 [0.32971124 0.85507943 1.90346186 1.00082277]
 [0.64905281 1.68804766 1.42643449 1.22049647]]


Bingo, it seems to work!

## Try it yourself (homework 3.3.1.3)

Now, write an alternative algorithm that scales $ A $ one row at a time.

Use the <a href="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/index.html"> Spark webpage </a> to generate the function Scale_a_matrix_unb_var2( beta, A ) that computes $ A := \beta A $ one row at a time.

In [4]:
import flame
import laff as laff

def Scale_a_matrix_unb_var2(beta, A):

    AT, \
    AB  = flame.part_2x1(A, \
                         0, 'TOP')

    while AT.shape[0] < A.shape[0]:

        A0,  \
        a1t, \
        A2   = flame.repart_2x1_to_3x1(AT, \
                                       AB, \
                                       1, 'BOTTOM')

        #------------------------------------------------------------#

        laff.scal( beta, a1t )

        #------------------------------------------------------------#

        AT, \
        AB  = flame.cont_with_3x1_to_2x1(A0,  \
                                         a1t, \
                                         A2,  \
                                         'TOP')

    flame.merge_2x1(AT, \
                    AB, A)





Test your routine with the following

In [5]:
from numpy import random
from numpy import matrix

beta = matrix( '2' );
A = matrix( random.rand( 5,4 ) )

print( 'A before =' )
print( A )

Scale_a_matrix_unb_var2( beta, A )
print( 'A after =' )
print( A )

A before =
[[0.6147516  0.12605902 0.4281251  0.93597628]
 [0.3984466  0.79749084 0.08289902 0.66362377]
 [0.16238158 0.56335967 0.51076689 0.92218844]
 [0.42880401 0.29027107 0.06727329 0.10892595]
 [0.08410681 0.12933509 0.27963107 0.7585791 ]]
A after =
[[1.22950319 0.25211804 0.8562502  1.87195256]
 [0.79689321 1.59498168 0.16579803 1.32724754]
 [0.32476316 1.12671933 1.02153379 1.84437689]
 [0.85760803 0.58054214 0.13454659 0.21785189]
 [0.16821363 0.25867019 0.55926214 1.5171582 ]]


## Watch your code in action!

Copy and paste the code into <a href="http://edx-org-utaustinx.s3.amazonaws.com/UT501x/PictureFlame/PictureFLAME.html"> PictureFLAME </a>, a webpage where you can watch your routine in action.  Just cut and paste into the box.  

Disclaimer: we implemented a VERY simple interpreter.  If you do something wrong, we cannot guarantee the results.  But if you do it right, you are in for a treat.

If you want to reset the problem, just click in the box into which you pasted the code and hit "next" again.