# Matrix-vector multiplication via <code>axpy</code>s

This notebook walks you through how to implement $ y := A x + y $ via axpy operations.

## Getting started

We will use some functions that are part of our laff library (of which this function will become a part) as well as some routines from the FLAME API (Application Programming Interface) that allows us to write code that closely resembles how we typeset algorithms using the FLAME notation.  These functions are imported with the "import laff as laff" and "import flame" statements.

## Algorithm

<image src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/342Mvmult_n_unb_var2.png" alt="Matrix-vector multiplication via dot products algorithm" width="75%">

## The routine <br> <code> Mvmult_n_unb_var2( A, x, y ) </code>

This routine, given $ A \in \mathbb{R}^{m \times n} $, $ x \in \mathbb{R}^n $, and $ y \in \mathbb{R}^m $, computes $ y := A x + y $.  The "_n_" indicates this is the "no transpose" matrix-vector multiplication.  What this means will become clear next week.

The specific laff function we will use is 
<ul>
<li> <code> laff.axpy( alpha, x, y ) </code> which computes $ y := \alpha x + y $.  </li>
</ul>

Use the <a href="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/index.html"> Spark webpage </a>.

In [1]:
import flame
import laff as laff

def Mvmult_n_unb_var2(A, x, y):

    AL, AR = flame.part_1x2(A, \
                            0, 'LEFT')

    xT, \
    xB  = flame.part_2x1(x, \
                         0, 'TOP')

    while AL.shape[1] < A.shape[1]:

        A0, a1, A2 = flame.repart_1x2_to_1x3(AL, AR, \
                                             1, 'RIGHT')

        x0,   \
        chi1, \
        x2    = flame.repart_2x1_to_3x1(xT, \
                                        xB, \
                                        1, 'BOTTOM')

        #------------------------------------------------------------#

        laff.axpy( chi1, a1, y )

        #------------------------------------------------------------#

        AL, AR = flame.cont_with_1x3_to_1x2(A0, a1, A2, \
                                            'LEFT')

        xT, \
        xB  = flame.cont_with_3x1_to_2x1(x0,   \
                                         chi1, \
                                         x2,   \
                                         'TOP')






## Testing

Let's quickly test the routine by creating a 4 x 3 matrix and related vectors, performing the computation.

In [2]:
from numpy import random
from numpy import matrix

A = matrix( random.rand( 4,3 ) )
x = matrix( random.rand( 3,1 ) )
y = matrix( random.rand( 4,1 ) )
yold = matrix( random.rand( 4,1 ) )

print( 'y before =' )
print( y )

print( 'x before =' )
print( x )

print( 'y before =' )
print( y )

y before =
[[0.75839901]
 [0.66109151]
 [0.95070205]
 [0.14433943]]
x before =
[[0.40975252]
 [0.22164808]
 [0.12656927]]
y before =
[[0.75839901]
 [0.66109151]
 [0.95070205]
 [0.14433943]]


In [3]:
laff.copy( y, yold )   # save the original vector y

Mvmult_n_unb_var2( A, x, y )

print( 'y after =' )
print( y )

print( 'y - ( A * x + yold ) = ' )
print( y - ( A * x + yold ) )

y after =
[[1.45219073]
 [1.15515869]
 [1.31601098]
 [0.42196862]]
y - ( A * x + yold ) = 
[[0.]
 [0.]
 [0.]
 [0.]]


Bingo, it seems to work!  (Notice that we are doing floating point computations, which means that due to rounding you may not get an exact "0".)

## Watch your code in action!

Copy and paste the code into <a href="http://edx-org-utaustinx.s3.amazonaws.com/UT501x/PictureFlame/PictureFLAME.html"> PictureFLAME </a>, a webpage where you can watch your routine in action.  Just cut and paste into the box.  

Disclaimer: we implemented a VERY simple interpreter.  If you do something wrong, we cannot guarantee the results.  But if you do it right, you are in for a treat.

If you want to reset the problem, just click in the box into which you pasted the code and hit "next" again.