# 8.2.4 Gauss-Jordan with Appended System to Invert a Matrix

<font color=red> Copy this notebook first! At each step, if you make a mistake, rerun all the cells above the current cell!!!</font>

<br>

With this notebook, we walk you through Homework 8.2.4.  

We start with the same appended system as in 8.2.4, except now we work with three right-hand sides, and pick those right-hand sides to be the unit basis vectors.  In other words, we append the identity matrix.

Let's set this up as an appended matrix and the application of Gauss transforms.  Here matrix $ A $ holds the appended system
$ 
\left( \begin{array}{ r r r | r r f}
-2 & 2 & -5 & 1 & 0 & 0 \\
2 & -3 & 7 & 0 & 1 & 0 \\
-4 & 3 & -7 & 0 & 0 & 1
\end{array} \right)
$

Fill in the ? in matrix $ A $.  Notice that the matrix on the left side of the appended system is the same as the matrix from 8.2.2 and 8.2.3. See what happens if you simply use the same Gauss transforms, and apply them to the appended system! 

In [1]:
import numpy as np

A = np.matrix( '-2,  2, -5,     1,  0,  0;\
                 2, -3,  7,     0,  1,  0;\
                -4,  3, -7,     0,  0,  1' )

print( 'A = ' )
print( A )

G0 = np.matrix( ' 1,  0,  0;\
                  1,  1,  0;\
                 -2,  0,  1' );

A0 = G0 * A

print( 'A0 = ' )
print( A0 )

A = 
[[-2  2 -5  1  0  0]
 [ 2 -3  7  0  1  0]
 [-4  3 -7  0  0  1]]
A0 = 
[[-2  2 -5  1  0  0]
 [ 0 -1  2  1  1  0]
 [ 0 -1  3 -2  0  1]]


If you did this right, the result matrix $ A_0 = G_0 A $ has zeroes in the off-diagonal entries of the first column, which then corresponds to the answer to the first step in Homework 8.2.4.1:

<img src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/8_2_4_1_QuestionA.png" width="75%"> </img>

The appended system is now represented by <code> A0 </code>:

In [2]:
print( 'A0 =' )
print( A0 )

A0 =
[[-2  2 -5  1  0  0]
 [ 0 -1  2  1  1  0]
 [ 0 -1  3 -2  0  1]]


Now, use $ G_1 $ from Homework 8.2.2.1 to introduce zeroes in the off-diagonal elemental of the second column of $ A_0 $:

In [3]:
G1 = np.matrix( ' 1,  2,  0;\
                  0,  1,  0;\
                  0, -1,  1' );

A1 = G1 * A0

print( 'A1 = ' )
print( A1 )

A1 = 
[[-2  0 -1  3  2  0]
 [ 0 -1  2  1  1  0]
 [ 0  0  1 -3 -1  1]]


If you did this right, the result matrix $ A_1 = G_1 A_0 = G_1 G_0 A $ has zeroes in the off-diagonal entries of the first column and the second column, which then corresponds to the answer to the second step in Homework 8.2.4.1:

<img src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/8_2_4_1_QuestionB.png" width="75%"> </img>

The appended system is now represented by <code> A1 </code>:

In [4]:
print( 'A1 =' )
print( A1 )

A1 =
[[-2  0 -1  3  2  0]
 [ 0 -1  2  1  1  0]
 [ 0  0  1 -3 -1  1]]


Now, use the $ G_2 $ from Homework 8.2.2 to introduce zeroes in the off-diagonal elemental of the third column of $ A_1 $:

In [5]:
G2 = np.matrix( ' 1,  0,  1;\
                  0,  1, -2;\
                  0,  0,  1' );

A2 = G2 * A1

print( 'A2 = ' )
print( A2 )

A2 = 
[[-2  0  0  0  1  1]
 [ 0 -1  0  7  3 -2]
 [ 0  0  1 -3 -1  1]]


If you did this right, the result matrix $ A_2 = G_2 A_1 = G_2 G_1 A_0 = G_2 G_1 G_0 A $ has zeroes in the off-diagonal entries of the first, second, and third column, which then corresponds to the answer to the third step in Homework 8.2.4.1:

<img src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/8_2_4_1_QuestionC.png" width="75%"> </img>

The appended system is now represented by <code> A2 </code>:

In [6]:
print( 'A2 =' )
print( A2 )

A2 =
[[-2  0  0  0  1  1]
 [ 0 -1  0  7  3 -2]
 [ 0  0  1 -3 -1  1]]


Now, use the diagonal matrix $ D $ from Homework 8.2.2 to set the diagonal elements in the appended system to one, making the first three columns into an identity matrix:

In [7]:
D = np.matrix( '-0.5,  0,  0;\
                  0,  -1,  0;\
                  0,  0,   1' );

A3 = D * A2

print( 'A3 = ' )
print( A3 )

A3 = 
[[ 1.   0.   0.   0.  -0.5 -0.5]
 [ 0.   1.   0.  -7.  -3.   2. ]
 [ 0.   0.   1.  -3.  -1.   1. ]]


If you did this right, the result matrix 

$ A_3 = D A_2 = D G_2 A_1 = D G_2 G_1 A_0 = D G_2 G_1 G_0 A $ 

has an identity in the first three columns, which then corresponds to the answer to the fourth step in Homework 8.2.4.1:

<img src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/8_2_4_1_QuestionD.png" width="75%"> </img>

If you did this right, the last three columns of the appended system now contain the inverse of the original matrix $ A $.

Let's see what happens if we create a matrix $ B $ from the last three columns, restore the matrix $ A $ to its original contents, and multiply $ A B $:

In [8]:
B = A3[ 0:3, 3:6 ]

print( 'B = ' )
print( B )

A = np.matrix( '-2,  2, -5;\
                 2, -3,  7;\
                -4,  3, -7' )

print( 'A = ' )
print( A )

print( 'B = ' )
print( B )

print( ' A * B = ' )
print( A * B )

B = 
[[ 0.  -0.5 -0.5]
 [-7.  -3.   2. ]
 [-3.  -1.   1. ]]
A = 
[[-2  2 -5]
 [ 2 -3  7]
 [-4  3 -7]]
B = 
[[ 0.  -0.5 -0.5]
 [-7.  -3.   2. ]
 [-3.  -1.   1. ]]
 A * B = 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Hopefully, yielded the answer to the last part of 8.2.4.1:

<img src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/8_2_4_1_QuestionE.png" width="75%"> </img>