# 8.2.3 Gauss-Jordan with Appended System and Multiple Right-Hand Sides - Answer

<font color=red> Copy this notebook first! At each step, if you make a mistake, rerun all the cells above the current cell!!!</font>

<br>

With this notebook, we walk you through Homework 8.2.3.  

We start with the same appended system as in 8.2.2, except now you want to add another right-hand side to the system:

Let's set this up as an appended matrix and the application of a Gauss transform.  Here matrix $ A $ holds the appended system
$ 
\left( \begin{array}{ r r r | r r }
-2 & 2 & -5 & -7 & 8 \\
2 & -3 & 7 & 11 & -13 \\
-4 & 3 & -7 & -9 & 9
\end{array} \right)
$

Fill in the ? in matrix $ A $.  Notice that if you completed notebook 8.2.2, this is the same original matrix.  See what happens if you simply use the same Gauss transforms, and apply them to the appended system with the new right hand sides! 

In [1]:
import numpy as np

A = np.matrix( '-2,  2, -5, -7,  8;\
                 2, -3,  7, 11,-13;\
                -4,  3, -7, -9,  9' )

print( 'A = ' )
print( A )

G0 = np.matrix( ' 1,  0,  0;\
                  1,  1,  0;\
                 -2,  0,  1' );

A0 = G0 * A

print( 'A0 = ' )
print( A0 )

A = 
[[ -2   2  -5  -7   8]
 [  2  -3   7  11 -13]
 [ -4   3  -7  -9   9]]
A0 = 
[[-2  2 -5 -7  8]
 [ 0 -1  2  4 -5]
 [ 0 -1  3  5 -7]]


If you did this right, the result matrix $ A_0 = G_0 A $ has zeroes in the off-diagonal entries of the first column, which then corresponds to the below answer to the first step in Homework 8.2.3.1:

<img src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/8_2_3_1_QuestionA.png" width="75%"> </img>

The appended system is now represented by <code> A0 </code>:

In [2]:
print( 'A0 =' )
print( A0 )

A0 =
[[-2  2 -5 -7  8]
 [ 0 -1  2  4 -5]
 [ 0 -1  3  5 -7]]


Now, use $ G_1 $ from Homework 8.2.2.1 to introduce zeroes in the off-diagonal elemental of the second column of $ A_0 $:

In [3]:
G1 = np.matrix( ' 1,  2,  0;\
                  0,  1,  0;\
                  0, -1,  1' );

A1 = G1 * A0

print( 'A1 = ' )
print( A1 )

A1 = 
[[-2  0 -1  1 -2]
 [ 0 -1  2  4 -5]
 [ 0  0  1  1 -2]]


If you did this right, the result matrix $ A_1 = G_1 A_0 = G_1 G_0 A $ has zeroes in the off-diagonal entries of the first column and the second column, which then corresponds to the below answer to the second step in Homework 8.2.3.1:

<img src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/8_2_3_1_QuestionB.png" width="75%"> </img>

The appended system is now represented by <code> A1 </code>:

In [4]:
print( 'A1 =' )
print( A1 )

A1 =
[[-2  0 -1  1 -2]
 [ 0 -1  2  4 -5]
 [ 0  0  1  1 -2]]


Now, use the $ G_2 $ from Homework 8.2.3 to introduce zeroes in the off-diagonal elemental of the third column of $ A_1 $:

In [5]:
G2 = np.matrix( ' 1,  0,  1;\
                  0,  1, -2;\
                  0,  0,  1' );

A2 = G2 * A1

print( 'A2 = ' )
print( A2 )

A2 = 
[[-2  0  0  2 -4]
 [ 0 -1  0  2 -1]
 [ 0  0  1  1 -2]]


If you did this right, the result matrix $ A_2 = G_2 A_1 = G_2 G_1 A_0 = G_2 G_1 G_0 A $ has zeroes in the off-diagonal entries of the first, second, and third column, which then corresponds to the below answer to the third step in Homework 8.2.3.1:

<img src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/8_2_3_1_QuestionC.png" width="75%"> </img>

The appended system is now represented by <code> A2 </code>:

In [6]:
print( 'A2 =' )
print( A2 )

A2 =
[[-2  0  0  2 -4]
 [ 0 -1  0  2 -1]
 [ 0  0  1  1 -2]]


Now, use the diagonal matrix $ D $ from Homework 8.2.3 to set the diagonal elements in the appended system to one, making the first three columns into an identity matrix:

In [7]:
D = np.matrix( '-0.5,  0,  0;\
                  0,  -1,  0;\
                  0,  0,   1' );

A3 = D * A2

print( 'A3 = ' )
print( A3 )

A3 = 
[[ 1.  0.  0. -1.  2.]
 [ 0.  1.  0. -2.  1.]
 [ 0.  0.  1.  1. -2.]]


If you did this right, the result matrix 

$ A_3 = D A_2 = D G_2 A_1 = D G_2 G_1 A_0 = D G_2 G_1 G_0 A $ 

has an identity matrix in the first three columns, which then corresponds to the below answer to the fourth step in Homework 8.2.3.1:

<img src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/8_2_3_1_QuestionD.png" width="75%"> </img>

If you did this right, the resulting matrix represents the solution to the equations

<img src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/8_2_3_1_QuestionE.png" width="75%"> </img>

Let's see what happens if we take the two right-hand side columns and check if they solve the two equations:

In [8]:
A = np.matrix( '-2,  2, -5;\
                 2, -3,  7;\
                -4,  3, -7' )

print( 'A = ' )
print( A )

x0 = np.matrix( '-1;\
                 -2;\
                  1' )

x1 = np.matrix( ' 2;\
                  1;\
                 -2' )

print( 'x0 = ' )
print( x0 )

print( ' A * x0 = ' )
print( A * x0 )

print( 'x1 = ' )
print( x1 )

print( ' A * x1 = ' )
print( A * x1 )

A = 
[[-2  2 -5]
 [ 2 -3  7]
 [-4  3 -7]]
x0 = 
[[-1]
 [-2]
 [ 1]]
 A * x0 = 
[[-7]
 [11]
 [-9]]
x1 = 
[[ 2]
 [ 1]
 [-2]]
 A * x1 = 
[[  8]
 [-13]
 [  9]]


Do they solve the two linear systems from homework 8.2.3.1?

<img src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/8_2_3_1_QuestionE.png" width="75%"> </img>