#     12.4.2 The Power Method

With this notebook, we demonstrate how the Power Method can be used to compute the eigenvector associated with the largest eigenvalue (in magnitude).

<font color=red> Be sure to make a copy!!!! </font>

We start by creating a matrix with known eigenvalues and eigenvectors

How do we do this?  
<ul>
  <li>
    We want a matrix that is not deficient, since otherwise the Power Method may not work. 
  </li>
  <li>
    Hence, $ A = V \Lambda V^{-1} $ for some diagonal matrix $ \Lambda $ and nonsingular matrix $ V $.  The eigenvalues are then on the diagonal of $ \Lambda $ and the eigenvectors are the columns of $ V $.
    </li>
    <li>
    So, let's pick the eigenvalues for the diagonal of $ \Lambda $ and let's pick a random matrix $ V $ (in the hopes that it has linearly independent columns) and then let's see what happens.  
    </li>
    </ul>

<font color=red> Experiment by changing the eigenvalues!  What happens if you make the second entry on the diagonal equal to -4?  Or what if you set 2 to -1? </font>

In [1]:
import numpy as np
import laff
import flame

Lambda = np.matrix( ' 4., 0., 0., 0;\
                      0., 3., 0., 0;\
                      0., 0., 2., 0;\
                      0., 0., 0., 1' )

lambda0 = Lambda[ 0,0 ]

V = np.matrix( np.random.rand( 4,4 ) )

# normalize the columns of V to equal one

for j in range( 0, 4 ):
    V[ :, j ] = V[ :, j ] / np.sqrt( np.transpose( V[:,j] ) * V[:, j ] )

A = V * Lambda * np.linalg.inv( V )

print( 'Lambda = ' )
print( Lambda)

print( 'V = ' )
print( V )

print( 'A = ' )
print( A )


Lambda = 
[[4. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 1.]]
V = 
[[0.03214997 0.545383   0.61531142 0.6479935 ]
 [0.66321239 0.41010085 0.19898599 0.58022516]
 [0.26860602 0.58759372 0.54039095 0.49193766]
 [0.69782986 0.43486583 0.53830666 0.03795432]]
A = 
[[-3.66430081 -1.72552935  8.27100935 -1.19061034]
 [-3.93357044  2.02807053  3.92687058  0.54381612]
 [-5.31008168 -0.9959967   9.2328236  -0.82296797]
 [-2.55799119  0.92499371  2.17017679  2.40340667]]


In [2]:
# Pick a random starting vector

x = np.matrix( np.random.rand( 4,1 ) )

for i in range(0,10):
    x = A * x 
    
    # normalize x to length one
    x = x / np.sqrt( np.transpose( x ) * x )
    
    print( 'Rayleigh quotient with vector x:', np.transpose( x ) * A * x / ( np.transpose( x ) * x ))
    print( 'inner product of x with v0     :', np.transpose( x ) * V[ :, 0 ] )
    print( ' ' )

Rayleigh quotient with vector x: [[3.90232311]]
inner product of x with v0     : [[0.93123164]]
 
Rayleigh quotient with vector x: [[4.12253497]]
inner product of x with v0     : [[0.92867681]]
 
Rayleigh quotient with vector x: [[4.18117762]]
inner product of x with v0     : [[0.9440786]]
 
Rayleigh quotient with vector x: [[4.18707228]]
inner product of x with v0     : [[0.96352343]]
 
Rayleigh quotient with vector x: [[4.16889947]]
inner product of x with v0     : [[0.97833532]]
 
Rayleigh quotient with vector x: [[4.14146456]]
inner product of x with v0     : [[0.98768999]]
 
Rayleigh quotient with vector x: [[4.11335771]]
inner product of x with v0     : [[0.99313839]]
 
Rayleigh quotient with vector x: [[4.08848238]]
inner product of x with v0     : [[0.99620192]]
 
Rayleigh quotient with vector x: [[4.06799172]]
inner product of x with v0     : [[0.99790032]]
 
Rayleigh quotient with vector x: [[4.05175507]]
inner product of x with v0     : [[0.99883782]]
 


In the above, 
 <ul>
 <li>
 The Rayleigh quotient should converge to 4.0 (slowly).
 </li>
 <li>
 The inner product of $ x $ and the first column of $ V $, $ v_0 $, should converge to 1 or -1 since eventually $ x $ should be in the direction of $ v_0 $ (or in the opposite direction).
 </li>
 </ul>
 
If you change the "3" on the diagonal to "-4", then you have two largest eigenvalues (in magnitude), and the vector $ x $ will end up in the space spanned by $ v_0 $ and $ v_1 $. 
 You can check this by looking at $ ( I - V_L ( V_L^T V_L )^{-1} V_L^T ) x $, where $V_L $ equals the matrix with $ v_0 $ and $ v_1 $ as its columns, to see if the vector orthogonal to $ {\cal C}( V_L ) $ converges to zero. This is seen in the following code block:



In [3]:
w = x - V[ :,0:2 ] * np.linalg.inv( np.transpose( V[ :,0:2 ] ) * V[ :,0:2 ] ) * np.transpose( V[ :,0:2 ] ) * x
    
print( 'Norm of component orthogonal: ', np.linalg.norm( w ) )

Norm of component orthogonal:  0.0002933587629397183
